### ISSUE TITLE
Support ES6 import

### ISSUE THREAD

**Issue by tyvdh** [readmeio/api#21]
Maybe I’m just dense but I’d really like my business logic to be able to include all of the wonders of ES6, Babel, etc. but it doesn’t seem I’m able. Or am I just dense and missing something? I was getting import unrecognized errors. I assume maybe this could be accomplished via some webpack jujitsu?

Curious what your recommendations are.

Thanks!

**Comment by domharrington** [comment]
Hey,

Can you give me a code sample of what is not supported? How are you transpiling your code right now? What version of node are you on?

Thanks

**Comment by tyvdh** [comment]
`import _ from 'lodash'`

I'm not transpiling which is what I'm guessing I need to do. Put webpack between the `endpoints` directory and the code I want to use while writing those endpoint files. Correct?

```shell
$ node -v
v8.6.0
```

**Comment by domharrington** [comment]
Hey!

Yeah you'll need to transpile if you want to use ES Modules because they're not currently supported in node. Additionally right now we're deploying to Lambda which uses node v6 which also limits what features we can use somewhat in your APIs.

We definitely need more docs on this. I recently discovered this module which allows you to use ES modules in current versions of node: https://github.com/standard-things/esm. We may be able to utilise this in some way? What do you think?

Dom

**Comment by tyvdh** [comment]
I don't think there's any need to support much by default. Just clarify what works and what doesn't in the docs and PLEASE include a more robust example or two using a compiler like webpack.

**Comment by domharrington** [comment]
Definitely I agree, thanks for trying us out! Have you managed to create any APIs yet? Did you have any other questions?

**Comment by tyvdh** [comment]
Nope and nope. I'll wait awhile while the product matures. Maybe for the next API I build I'll give it a go. Love the idea, just a bit too limited/confusing for now.

**Comment by domharrington** [comment]
Thanks for the feedback! We're working on it. Be sure to check back in the following weeks/months.
