### ISSUE TITLE
ability to pass specific headers

### ISSUE THREAD

**Issue by heaversm** [readmeio/api#433]
I am using an API that requires the API Key to be passed in the headers (doesn't seem to support the `.auth([API_KEY])` method provided by this module). How do I pass the key in the headers? Here's my current implementation:

```
const sdk = require("api")("@sublimesecurity/v0.3#49y4gl02wflaz");
sdk.server("https://emailrep.io");
sdk
    .auth(API_KEY) //MH TODO: doesn't seem to change rate limiting, is this working?
    .get(`/${email}`)
    .then((data) => { ... })

```

**Comment by erunion** [comment]
Hey it looks like we aren't able to send auth on the `/{email}` endpoint because it doesn't specify any auth requirements. Note no `security` definition here:

![Screen Shot 2022-04-19 at 12 15 23 PM](https://user-images.githubusercontent.com/33762/164078854-1bab2135-e195-420d-bb45-9af1c61666dd.png)

Unfortunately `api` is extremely opinionated about how to handle auth so it's hard to tell it to use auth when a spec says you don't need it, and due to `api`'s payload structure of `body` and `metadata` objects there's no way for you to pass in  the `Key` header as an argument here.

We're still working on improving the syntax of `api` and I'm open to maybe an `sdk.header()` method addition for these cases, but in the meantime I'd recommend reaching out to Sublime Security and get them to update their OpenAPI file.

**Comment by heaversm** [comment]
Thanks - super helpful. I'm not super savvy with this stuff - how did you get the JSON for their openAPI structure?

**Comment by erunion** [comment]
The UUID string in the accessor of your snippet (`@sublimesecurity/v0.3#49y4gl02wflaz`), maps to an OpenAPI definition entry within our API Registry and can be accessed through our [`/api-registry` API endpoint](https://docs.readme.com/reference/getapiregistry ).

```
https://dash.readme.com/api/v1/api-registry/49y4gl02wflaz
```

Since you've run this code locally as well you have a copy of the API definition on your system too under `node_modules/.cache/api`. You might actually be able to get this API endpoint that doesn't have required auth working by editing that API definition locally, but things will break if that cache gets deleted with an `npm ci` so YMMV.

**Comment by StewartJ-SSG** [comment]
@erunion - this was super helpful, thank you. I've been trying to grab an api spec from the readme archive and I did not understand that the UUID portion of the string was ONLY the portion AFTER the # sign! It would be really helpful if the [docs](https://api.readme.dev/docs/installation) could indicate that and give example URL like the one you gave above.

**Comment by erunion** [comment]
@StewartJ-SSG Thanks, I just saw your edit suggestion. I've pulled it in in https://github.com/readmeio/api/commit/a9c6ce28b3bcb6981e2135180c19f39ef6f025af.
