### ISSUE TITLE
missing parameter var

### ISSUE THREAD

**Issue by isragal** [readmeio/api#626]
Error while trying to install Yotpo api

https://apidocs.yotpo.com/reference/create-review
npx api install @yotpo/v1.0#d5n9g32blfb6qkpb 

![image](https://user-images.githubusercontent.com/23261549/225646125-8c55d6c5-7f1a-4ab1-8321-06d103e3fb20.png)

is there a way to pass params on installation?

**Comment by erunion** [comment]
This is unfortunately happening because Yotpo has created some API URLs that aren't valid to the OpenAPI Spec and we don't validate those there.

You might want to reach out to them to have them change the path for `/apps/{app_key}/subomain_check/{subdomain}?utoken={utoken}` to `/apps/{app_key}/subomain_check/{subdomain}` as it seems like they're already documenting `utoken` as a query parameter.
